version: '3'

services:
  db:
    image: roadkill/db
    restart: always
    build: ./data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${DEV_POSTGRES_PASSWORD}
      - POSTGRES_DB=app
  api:
    build: ./src/back
    ports:
      - '3000:3000'

volumes:
  pgdata:
