version: '3'

services:
  db:
    image: roadkill/db
    restart: always
    build:
      context: .
      dockerfile: ./data/CloudSql.Dockerfile
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${DEV_POSTGRES_PASSWORD}
      - POSTGRES_DB=app

volumes:
  pgdata:
