name: Perform Database Migrations
description: Perform database migrations if necessary.
inputs:
  environment:
    description: environment
    required: true
  project_id:
    description: the gcp project id
    required: true
  identity_provider:
    description: gcp federation identity provider
    required: true
  service_account_email:
    description: gcp service account email
    required: true
  cloudsql_instance:
    description: cloud sql instance name
    required: true

runs:
  using: composite
  steps:
    - id: auth
      name: 🗝️ Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        token_format: access_token
        workload_identity_provider: ${{ inputs.identity_provider }}
        service_account: ${{ inputs.service_account_email }}

    - name: Initialize Cloud SQL Auth Proxy
      shell: bash
      run: |
        URL="https://storage.googleapis.com/cloud-sql-connectors/cloud-sql-proxy/v2.14.3"
        curl "$URL/cloud-sql-proxy.linux.amd64" -o cloud-sql-proxy
        chmod +x cloud-sql-proxy
        ./cloud-sql-proxy ${{ inputs.cloudsql_instance }} --port 5432 &

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: data/.node-version

    - name: Install npm dependencies
      shell: bash
      working-directory: data
      run: |
        npm ci
        npm install -g knex

    - name: Run knex migrations
      shell: bash
      working-directory: data
      run: |
        knex migrate:latest --env ${{ inputs.environment }}
