name: Back - Test, Build, and Deploy to GCP

on:
  push:
    branches:
      - staging
      - production
    paths:
      - 'src/back/**'
      - '.github/workflows/back.yml'

env:
  SERVICE_NAME: api

defaults:
  run:
    working-directory: src/back

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # this could be removed once setup-node adds support for .nvmrc files
      # ref: https://github.com/actions/setup-node/issues/32
      - name: Get node version
        id: nvm
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.nvm.outputs.NODE_VERSION }}
      - run: npm ci

      - name: setup gcloud
        uses: google-github-actions/setup-gcloud@master

      - name: install gcloud beta components
        run: |
          gcloud components install beta
          gcloud components install cloud-datastore-emulator

      - name: Test
        run: npm run test:ci

  deploy-staging:
    name: Build and Deploy to Staging
    runs-on: ubuntu-latest
    needs: test
    environment:
      name: Staging
    if: github.ref == 'refs/heads/staging'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get Variables
        id: variables
        shell: bash
        run: |
          PROJECT_ID="${{ secrets.PROJECT_ID }}"
          echo "::set-output name=image::gcr.io/$PROJECT_ID/$SERVICE_NAME"

      # this could be removed once setup-node adds support for .nvmrc files
      # ref: https://github.com/actions/setup-node/issues/32
      - name: Get node version
        id: nvm
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.nvm.outputs.NODE_VERSION }}
      - run: npm ci

      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          project_id: ${{ secrets.PROJECT_ID }}

      - run: |-
          gcloud --quiet auth configure-docker

      - name: Build Image
        run: |-
          docker build \
            -t "${{ steps.variables.outputs.image }}:$GITHUB_SHA" \
            -t "${{ steps.variables.outputs.image }}:latest" \
            .

      - name: Publish Image
        run: |-
          docker push "${{ steps.variables.outputs.image }}" -a

      - name: Deploy
        run: |-
          gcloud run deploy "$SERVICE_NAME" \
            --quiet \
            --platform "managed" \
            --region "us-central1" \
            --image "${{ steps.variables.outputs.image }}:latest" \
            --update-env-vars \
              DATABASE_HOST=${{ secrets.DATABASE_HOST }},\
              DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }},\
              SENDGRID_API_KEY=${{ secrets.SENDGRID_API_KEY }},\
              API=${{ secrets.API }}
              ADMIN_EMAIL=${{ secrets.ADMIN_EMAIL }}

  deploy-prod:
    name: Build and Deploy to Production
    runs-on: ubuntu-latest
    needs: test
    environment:
      name: Production
    if: github.ref == 'refs/heads/production'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get Variables
        id: variables
        shell: bash
        run: |
          PROJECT_ID="${{ secrets.PROJECT_ID }}"
          echo "::set-output name=image::gcr.io/$PROJECT_ID/$SERVICE_NAME"

      # this could be removed once setup-node adds support for .nvmrc files
      # ref: https://github.com/actions/setup-node/issues/32
      - name: Get node version
        id: nvm
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.nvm.outputs.NODE_VERSION }}
      - run: npm ci

      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          project_id: ${{ secrets.PROJECT_ID }}

      - run: |-
          gcloud --quiet auth configure-docker

      - name: Build Image
        run: |-
          docker build \
            -t "${{ steps.variables.outputs.image }}:$GITHUB_SHA" \
            -t "${{ steps.variables.outputs.image }}:latest" \
            .

      - name: Publish Image
        run: |-
          docker push "${{ steps.variables.outputs.image }}" -a

      - name: Deploy
        run: |-
          gcloud run deploy "$SERVICE_NAME" \
            --quiet \
            --platform "managed" \
            --region "us-central1" \
            --image "${{ steps.variables.outputs.image }}:latest" \
            --update-env-vars \
              DATABASE_HOST=${{ secrets.DATABASE_HOST }},\
              DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }},\
              SENDGRID_API_KEY=${{ secrets.SENDGRID_API_KEY }},\
              API=${{ secrets.API }}
              ADMIN_EMAIL=${{ secrets.ADMIN_EMAIL }}
