name: Back - Test, Build, and Deploy to GCP

on:
  push:
    paths:
      - 'src/back/**'
      - '.github/workflows/back.yml'
      - '.github/actions/back/**'

env:
  SERVICE_NAME: api

defaults:
  run:
    working-directory: src/back

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        id: cache
        with:
          path: ~/.cache/firebase/emulators
          key: ${{ runner.os }}-firebase-emulators-${{ hashFiles('~/.cache/firebase/emulators/**') }}

      # this could be removed once setup-node adds support for .nvmrc files
      # ref: https://github.com/actions/setup-node/issues/32
      - name: Get node version
        id: nvm
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.nvm.outputs.NODE_VERSION }}
      - run: |
          npm ci
          cd ../common && npm ci

      - name: Test
        run: |
          npm run lint
          npm run test:ci

  deploy-staging:
    name: Build and Deploy to Staging
    runs-on: ubuntu-latest
    needs: test
    environment:
      name: Staging
    if: github.ref == 'refs/heads/staging'
    env:
      PROJECT_ID: ${{ secrets.PROJECT_ID }}
      SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}
      ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}
      API: ${{ secrets.API }}
      DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy
        uses: ./.github/actions/back/deploy
        with:
          environment: Staging

  deploy-prod:
    name: Build and Deploy to Production
    runs-on: ubuntu-latest
    needs: test
    environment:
      name: Production
    if: github.ref == 'refs/heads/production'

    env:
      PROJECT_ID: ${{ secrets.PROJECT_ID }}
      SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}
      ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}
      API: ${{ secrets.API }}
      DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy
        uses: ./.github/actions/back/deploy
        with:
          environment: Production
