name: Front - Test

on:
  push:
    paths:
      - 'src/front/**'
      - '.github/workflows/front.yml'
      - '.github/actions/front/**'
      - 'CHANGELOG.md'
      - 'changelog_context.json'
      - 'src/common/**'

defaults:
  run:
    working-directory: src/front

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Use HTTPS instead of SSH to install dependencies from GitHub repos
      # See: https://github.com/actions/setup-node/issues/214#issuecomment-810829250
      # this could be removed once git-rev-sync is pointed back at the upstream repo
      - name: Reconfigure git to use HTTP authentication
        run: >
          git config --global url."https://github.com/".insteadOf
          ssh://git@github.com/

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: lts/*

      - name: Install npm dependencies
        run: |
          npm ci
          cd ../common && npm ci

      - name: Test
        run: npm run test:final
