name: Test, Build, and Deploy

on:
  push:
    branches:
      - staging
      #: TODO: switch to main after release
      - rewrite
    paths:
      - 'src/front/**'
      - '.github/workflows/front.yml'

defaults:
  run:
    working-directory: src/front

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # this could be removed once setup-node adds support for .nvmrc files
      # ref: https://github.com/actions/setup-node/issues/32
      - name: Get node version
        id: nvm
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.nvm.outputs.NODE_VERSION }}
      - run: npm ci

      - name: Test
        run: npm test -- --watch=false
