name: Front - Test

on:
  push:
    paths:
      - 'src/front/**'
      - '.github/workflows/front.yml'
      - '.github/actions/front/**'
      - 'CHANGELOG.md'
      - 'changelog_context.json'
      - 'src/common/**'

defaults:
  run:
    working-directory: src/front

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: src/front/.node-version

      - name: Install npm dependencies
        run: |
          npm ci
          cd ../common && npm ci

      - name: Test
        run: npm run test:final
